project:
  type: website

website:
  title: "Nalanda"
  navbar:
    background: "#8a6642"  # Earthy brown color
    foreground: "#f8f5e6"  # Light cream color
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - work.qmd
      - blog.qmd
  page-footer:
    center: 
      - text: " 2025 Nalanda. All rights reserved."
    background: "#8a6642"
    foreground: "#f8f5e6"
    left:
      - text: "Built with [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    page-background: "images/buddhist-watercolor-bg.jpg"
    mainfont: "Noto Serif"
